### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by nolimits4web** [reapp/kitchen-sink#2]
After installing all dependancies and running `reapp run` i go this error in terminal:

```
WARNING in ./app/routes.js
Critical dependencies:
6:16-23 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./app/routes.js 6:16-23
```

And of course, nothing works on localhost:3011, i see just directories listing

**Comment by natew** [comment]
You want to go to [http://localhost:3010](http://localhost:3010), the 3011 port is for webpack to serve assets from.
